baseURL = 'https://nhathadt11.github.io/blog/'
languageCode = 'en-us'
title = "nhatha.dev"
theme = "ezhil"

copyright = "© nhatha.dev"

pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# googleAnalytics = "UA-123-45"
# disqusShortname = "hes-blog"

summaryLength = 20

[params]
	subtitle = "Personal blog"
	disableDisqusTypes = ["page"]
	featherIconsCDN = true
	customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	customDarkCss = "css/customdark.css"
	mode = "auto" # "dark", "auto", "light"

[[menu.main]]
	name = "Home"
	url = "/"
	weight = 1

[[menu.main]]
	name = "All posts"
	url = "/posts"
	weight = 2

[[menu.main]]
	name = "Tags"
	url = "/tags"
	weight = 3

[[menu.main]]
	name = "About"
	url = "/about"
	weight = 4

[[params.social]]
	name = "Github"
	icon = "github"
	url = "https://github.com/nhathadt11"

[taxonomies]
   	tag = "tags"