baseURL = 'https://nhathadt11.github.io/blog/'
languageCode = 'en-us'
title = "nhatha.dev"
theme = "ezhil"

copyright = "© nhatha.dev"

pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "G-6B98FZY2PW"
# disqusShortname = "hes-blog"

summaryLength = 20

[params]
	subtitle = "Personal blog"
	disableDisqusTypes = ["page"]
	featherIconsCDN = true
	customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	customDarkCss = "css/customdark.css"
	mode = "auto" # "dark", "auto", "light"
	googleAnalytics = "G-6B98FZY2PW"
	katex = true

[[menu.main]]
	name = "Home"
	url = "/"
	weight = 1

[[menu.main]]
	name = "All posts"
	url = "/posts"
	weight = 2

[[menu.main]]
	name = "Tags"
	url = "/tags"
	weight = 3

[[menu.main]]
	name = "Search"
	url = "/search"
	weight = 4

[[menu.main]]
	name = "About"
	url = "/about"
	weight = 5

[[params.social]]
	name = "Github"
	icon = "github"
	url = "https://github.com/nhathadt11"

[[params.social]]
	name = "Linkedin"
	icon = "linkedin"
	url = "https://linkedin.com/in/nhathadt11"

[[params.social]]
	name = "Mail"
	icon = "mail"
	url = "mailto:me@nhatha.dev"

[[params.social]]
	name = "Key"
	icon = "key"
	url = "https://keyserver.ubuntu.com/pks/lookup?search=me%40nhatha.dev&fingerprint=on&op=index"

[[params.social]]
	name = "RSS"
	icon = "rss"
	url = "/index.xml"

[taxonomies]
   	tag = "tags"