baseURL = 'https://nhathadt11.github.io/blog/'
languageCode = 'en-us'
title = "Rihe's Blog"
theme = "ezhil"

copyright = "© Rihe"

pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# googleAnalytics = "UA-123-45"
# disqusShortname = "hes-blog"

summaryLength = 20

[params]
	subtitle = "Personal blog "
	disableDisqusTypes = ["page"]
	featherIconsCDN = true
	customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	customDarkCss = "css/customdark.css"
	mode = "auto" # "dark", "auto", "light"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/nhathadt11"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"